#!/bin/sh

bspc config top_padding 25

# Visual options
bspc config split_ratio 0.50
bspc config border_width 3
bspc config window_gap 20
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cancel true

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config normal_border_color "#504339"
bspc config active_border_color "#504339"
bspc config focused_border_color "#817267"
bspc config presel_border_color "#9a875f"
bspc config urgent_border_color "#504339"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

bspc monitor -d web dev social xxx
bspc monitor VGA1 -d one two three four

bspc rule -a feh floating=on
bspc rule -a pavucontrol floating=on
bspc rule -a Thunar floating=on
bspc rule -a gifview floating=on
bspc rule -a lxappearance floating=on
bspc rule -a OzTools floating=on
bspc rule -a scratchpad floating=on

bspc rule -a Dmenu border=on

bspc rule -a Popup border=off

panel &
